import { auth, db, authPersistenceReady } from "../login/firebase-config.js?v=6";
import { onAuthStateChanged, signOut } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js";
import { ref, onValue } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-database.js";
const period=document.body.dataset.period;let receipts=[];let unsubscribe=null;let dayDetail=false;
const won=n=>new Intl.NumberFormat("ko-KR").format(Math.round(n||0))+"원";
const key=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
const dateOf=r=>new Date(`${r.date||"1970-01-01"}T${r.time||"00:00"}:00`);
function startOfWeek(d){const x=new Date(d),day=x.getDay();x.setDate(x.getDate()-(day===0?6:day-1));x.setHours(0,0,0,0);return x}function addDays(d,n){const x=new Date(d);x.setDate(x.getDate()+n);return x}function fmt(d,o={}){return new Intl.DateTimeFormat("ko-KR",o).format(d)}function sum(rs){return rs.reduce((a,r)=>a+Number(r.amount||0),0)}function sameDate(r,d){return r.date===key(d)}function inRange(r,a,b){const d=dateOf(r);return d>=a&&d<b}
function selectedDay(){const p=new URLSearchParams(location.search).get("date");if(/^\d{4}-\d{2}-\d{2}$/.test(p||"")){const[y,m,d]=p.split("-").map(Number),x=new Date(y,m-1,d);if(x.getFullYear()===y&&x.getMonth()===m-1&&x.getDate()===d)return x}return new Date()}
function currentData(){const now=new Date();now.setHours(0,0,0,0);if(period==="day"){const s=selectedDay();s.setHours(0,0,0,0);return{start:s,end:addDays(s,1)}}if(period==="week"){const s=startOfWeek(now);return{start:s,end:addDays(s,7)}}if(period==="month"){const s=new Date(now.getFullYear(),now.getMonth(),1);return{start:s,end:new Date(now.getFullYear(),now.getMonth()+1,1)}}const s=new Date(now.getFullYear(),0,1);return{start:s,end:new Date(now.getFullYear()+1,0,1)}}
const labels={day:"일별",week:"주별",month:"달별",year:"연별"};const descriptions={day:"하루의 지출을 실제 결제 시간 기준으로 확인하세요.",week:"한 주를 달력으로 보면서 어느 날 지출했는지 확인하세요.",month:"이번 달의 소비 흐름을 달력과 함께 확인하세요.",year:"올해 12개월의 지출 흐름을 한눈에 확인하세요."};
function render(){const{start,end}=currentData(),current=receipts.filter(r=>inRange(r,start,end));document.querySelector("#periodTotal").textContent=won(sum(current));document.querySelector("#periodCount").textContent=`${current.length}장`;document.querySelector("#avgAmount").textContent=won(current.length?sum(current)/current.length:0);document.querySelector("#welcome").textContent=`${window.receiptUserName||"사용자"}님의 ${labels[period]} 지출`;const descEl=document.querySelector("#description");if(descEl)descEl.textContent=descriptions[period];if(period==="day")renderDay(start);else if(period==="week")renderWeek(start);else if(period==="month")renderMonth(start);else renderYear(start);renderCategories(current);renderReceipts(current);if(period==="day")updateDayControls(start)}
function renderDay(start){const rs=receipts.filter(r=>sameDate(r,start));let html;if(dayDetail){const vals=Array.from({length:24},(_,h)=>sum(rs.filter(r=>dateOf(r).getHours()===h))),max=Math.max(...vals,1);html=`<div class="day-hours">${vals.map((v,h)=>`<div class="hour-row"><span class="hour-label">${String(h).padStart(2,"0")}시</span><div class="hour-track"><i style="width:${v?Math.max(v/max*100,4):0}%"></i></div><strong>${v?won(v):"-"}</strong></div>`).join("")}</div>`}else{const groups=Array.from({length:6},(_,i)=>{const from=i*4,items=rs.filter(r=>{const h=dateOf(r).getHours();return h>=from&&h<from+4});return{from,to:from+3,total:sum(items),count:items.length}}),max=Math.max(...groups.map(g=>g.total),1);html=`<div class="four-hour-grid">${groups.map(g=>`<div class="four-hour-card"><div class="four-hour-label">${String(g.from).padStart(2,"0")}시 ~ ${String(g.to).padStart(2,"0")}시</div><strong>${won(g.total)}</strong><span>${g.count}건</span><div class="four-hour-track"><i style="width:${g.total?Math.max(g.total/max*100,5):0}%"></i></div></div>`).join("")}</div>`}document.querySelector("#specialView").innerHTML=html;document.querySelector("#specialHint").innerHTML=`<span>${dayDetail?"시간별 상세":"4시간 단위"}</span><button id="dayDetailBtn" class="detail-btn" type="button">${dayDetail?"간단히 보기":"자세히 보기"}</button>`;document.querySelector("#dayDetailBtn").onclick=()=>{dayDetail=!dayDetail;renderDay(start)}}
function renderWeek(start){const days=Array.from({length:7},(_,i)=>addDays(start,i));document.querySelector("#specialView").innerHTML=`<div class="week-calendar">${days.map(d=>{const rs=receipts.filter(r=>sameDate(r,d));return `<div class="week-day ${key(d)===key(new Date())?"today":""}"><div class="week-day-head"><span>${["월","화","수","목","금","토","일"][d.getDay()===0?6:d.getDay()-1]}</span><b>${d.getDate()}</b></div><div class="week-day-total">${sum(rs)?won(sum(rs)):"-"}</div><div class="week-dots">${rs.slice(0,3).map(()=>"<i></i>").join("")}</div></div>`}).join("")}</div>`}
function renderMonth(start){const first=new Date(start.getFullYear(),start.getMonth(),1),days=new Date(start.getFullYear(),start.getMonth()+1,0).getDate(),offset=(first.getDay()+6)%7;let cells="";for(let i=0;i<offset;i++)cells+='<div class="month-cell empty-cell"></div>';for(let n=1;n<=days;n++){const d=new Date(start.getFullYear(),start.getMonth(),n),t=sum(receipts.filter(r=>sameDate(r,d)));cells+=`<div class="month-cell ${key(d)===key(new Date())?"today":""}"><span>${n}</span>${t?`<strong>${won(t).replace("원","")}</strong>`:""}</div>`}document.querySelector("#specialView").innerHTML=`<div class="calendar-weekdays">${["월","화","수","목","금","토","일"].map(x=>`<span>${x}</span>`).join("")}</div><div class="month-calendar">${cells}</div>`}
function renderYear(start){const vals=Array.from({length:12},(_,i)=>sum(receipts.filter(r=>r.date?.startsWith(`${start.getFullYear()}-${String(i+1).padStart(2,"0")}`)))),max=Math.max(...vals,1);document.querySelector("#specialView").innerHTML=`<div class="year-grid">${vals.map((v,i)=>`<div class="year-month"><span>${i+1}월</span><strong>${won(v)}</strong><div class="year-track"><i style="height:${v?Math.max(v/max*100,6):2}%"></i></div></div>`).join("")}</div>`}
function renderCategories(rs){const cats=["식비","카페","쇼핑","교통","의료","기타"],vals=cats.map(c=>({c,v:sum(rs.filter(r=>r.category===c))})),max=Math.max(...vals.map(x=>x.v),1);document.querySelector("#categories").innerHTML=vals.map(x=>`<div class="cat-row"><span class="cat-name">${x.c}</span><div class="track"><div class="fill" style="width:${x.v/max*100}%"></div></div><span class="cat-amount">${won(x.v)}</span></div>`).join("")}
function renderReceipts(rs){const sorted=[...rs].sort((a,b)=>dateOf(b)-dateOf(a));document.querySelector("#receipts").innerHTML=sorted.length?sorted.slice(0,50).map(r=>`<div class="receipt"><div class="icon">▣</div><div><strong>${String(r.store??"")}</strong><span>${String(r.item??"")} · ${String(r.category??"")}</span></div><span class="date">${r.date??""} ${r.time??""}</span><strong class="amount">${won(r.amount)}</strong></div>`).join(""):`<div class="empty"><b>아직 영수증이 없어요</b>영수증을 추가하면 이곳에 자동으로 모아집니다.</div>`}
function updateDayControls(date){const p=document.querySelector("#prevDay"),n=document.querySelector("#nextDay"),t=document.querySelector("#todayDay");if(!p)return;const today=key(new Date()),selected=key(date);p.onclick=()=>location.href=`./?date=${key(addDays(date,-1))}`;t.onclick=()=>location.href="./";n.disabled=selected>=today;n.onclick=()=>{if(selected<today)location.href=`./?date=${key(addDays(date,1))}`}}
onAuthStateChanged(auth,user=>{if(!user){location.replace("../login/");return}window.receiptUserName=user.displayName?.trim()||user.email?.split("@")[0]||"사용자";if(unsubscribe)unsubscribe();unsubscribe=onValue(ref(db,`users/${user.uid}/receipts`),snap=>{receipts=Object.entries(snap.val()||{}).map(([id,r])=>({id,...r}));render()})});const doLogout=async()=>{await authPersistenceReady;await signOut(auth);location.replace("../login/")};document.querySelector("#logout").onclick=doLogout;document.querySelector("#mobileLogoutBtn")?.addEventListener("click",doLogout);